# Generated by Django 3.1.1 on 2026-02-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remote_User', '0007_clientposts_model_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='detection_accuracy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='detection_ratio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='traffic_accident_detection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fid', models.CharField(max_length=3000)),
                ('Accident_Index', models.CharField(max_length=3000)),
                ('Longitude', models.CharField(max_length=3000)),
                ('Latitude', models.CharField(max_length=3000)),
                ('Police_Force', models.CharField(max_length=3000)),
                ('Accident_Severity', models.CharField(max_length=3000)),
                ('Number_of_Vehicles', models.CharField(max_length=3000)),
                ('Number_of_Casualties', models.CharField(max_length=3000)),
                ('ADate', models.CharField(max_length=3000)),
                ('Day_of_Week', models.CharField(max_length=3000)),
                ('ATime', models.CharField(max_length=3000)),
                ('first_Road_Class', models.CharField(max_length=3000)),
                ('first_Road_Number', models.CharField(max_length=3000)),
                ('Road_Type', models.CharField(max_length=3000)),
                ('Speed_limit', models.CharField(max_length=3000)),
                ('Junction_Control', models.CharField(max_length=3000)),
                ('second_Road_Class', models.CharField(max_length=3000)),
                ('second_Road_Number', models.CharField(max_length=3000)),
                ('Light_Conditions', models.CharField(max_length=3000)),
                ('Weather_Conditions', models.CharField(max_length=3000)),
                ('Road_Surface_Conditions', models.CharField(max_length=3000)),
                ('Prediction', models.CharField(max_length=3000)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientposts_model',
            name='userId',
        ),
        migrations.DeleteModel(
            name='review_Model',
        ),
        migrations.AddField(
            model_name='clientregister_model',
            name='address',
            field=models.CharField(default='Not Provided', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientregister_model',
            name='gender',
            field=models.CharField(default='Not Provided', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='phoneno',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='ClientPosts_Model',
        ),
    ]
